version: '3.7'

# See run instructions in accompanying Dockerfile
services:

  usaspending-db:
    container_name: usaspending-db
    image: postgres:10.6-alpine
    volumes:
      - type: bind
        source: ${POSTGRES_CLUSTER_DIR}
        target: /var/lib/postgresql/data
    restart: on-failure:3 # Will attempt to start the db 3 times
    ports:
      - ${POSTGRES_PORT}:5432
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: data_store_api

  usaspending-manage:
    build: .
    volumes:
     - .:/dockermount
    command: /bin/sh -c "python -u manage.py shell"
    environment:
      DATABASE_URL: postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@${POSTGRES_HOST}:${POSTGRES_PORT}/data_store_api

  usaspending-db-sql:
    build: .
    volumes:
     - .:/dockermount
    command: >
      /bin/sh -c "mkdir $$MATVIEW_SQL_DIR | true &&
      python -u usaspending_api/database_scripts/matview_generator/matview_sql_generator.py --dest=$$MATVIEW_SQL_DIR"
    environment:
      MATVIEW_SQL_DIR: ${MATVIEW_SQL_DIR}

  usaspending-db-init:
    image: postgres:10.6-alpine
    volumes:
     - .:/dockermount
    command: >
      /bin/sh -c "cd /dockermount &&
      psql $$DATABASE_URL -c 'CREATE ROLE readonly' || true &&
      psql $$DATABASE_URL -f usaspending_api/database_scripts/matviews/functions_and_enums.sql &&
      cat $$MATVIEW_SQL_DIR/*.sql | psql $$DATABASE_URL -f -"
    environment:
      MATVIEW_SQL_DIR: ${MATVIEW_SQL_DIR}
      DATABASE_URL: postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@${POSTGRES_HOST}:${POSTGRES_PORT}/data_store_api

  usaspending-api:
    build: .
    volumes:
      - .:/dockermount
    ports:
      - 8000:8000
    command: /bin/sh -c "python -u manage.py runserver 0.0.0.0:8000"
    environment:
      DATABASE_URL: postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@${POSTGRES_HOST}:${POSTGRES_PORT}/data_store_api
      DOWNLOAD_DATABASE_URL: postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@${POSTGRES_HOST}:${POSTGRES_PORT}/data_store_api
      ES_HOSTNAME: ${ES_HOSTNAME}

  usaspending-es:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.2.4
    environment:
    - cluster.name=usaspending
    - network.host=0.0.0.0
    - bootstrap.memory_lock=true
    - "ES_JAVA_OPTS=-Xms1536m -Xmx1536m"  # Ensure Docker is allocated plenty of memory, otherwise this will fail
    - "discovery.zen.ping.unicast.hosts=usaspending-es"
    - discovery.zen.minimum_master_nodes=1
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
    - type: bind
      source: ${ES_CLUSTER_DIR}
      target: /usr/share/elasticsearch/data
    ports:
    - 9200:9200
