name: Reusable Broker branch workflow

on:
  workflow_call:
    outputs:
      branch:
        description: "broker-branch"
        value: ${{ jobs.Setup-Variables.outputs.broker-branch }}

jobs:
  # This job is a workaround that allows defining a dynamic variable that is provided as input
  # to another job. See here: https://github.com/orgs/community/discussions/26671#discussioncomment-3931817
  Setup-Variables:
    name: Setup Variables
    runs-on: ${{ vars.RUNNER_VERSION }}
    outputs:
      broker-branch: ${{ steps.determine-broker-branch.outputs.branch }}
    steps:
      - name: Determine Broker Branch
        id: determine-broker-branch
        run: |
          # Choose a branch that matches the target, otherwise, default to qat
          echo "branch=${{ contains(fromJSON('["qat", "staging", "master"]'), github.base_ref) && github.base_ref || 'qat' }}" >> "$GITHUB_OUTPUT"